version: 2

models:
  # --- Model Dimensi Customer ---
  - name: dim_customer
    description: "Tabel dimensi yang menyimpan data nasabah/pelanggan yang sudah dibersihkan."
    columns:
      - name: customer_key
        description: "Primary Key pelanggan (Surrogate/Natural Key)."
        tests:
          - unique    # Memastikan tidak ada duplikat ID
          - not_null  # Memastikan tidak ada nilai kosong

      - name: email
        description: "Alamat email pelanggan."
        tests:
          - not_null

  # --- Model Dimensi Product ---
  - name: dim_product
    description: "Daftar unik produk yang dijual."
    columns:
      - name: product_name
        description: "Nama produk (berfungsi sebagai Natural Key di sini)."
        tests:
          - unique
          - not_null

  # --- Model Fakta Orders ---
  - name: fact_orders
    description: "Tabel fakta transaksi penjualan detail (per item barang)."
    columns:
      - name: order_id
        description: "ID Transaksi dari sistem sumber."
        tests:
          - not_null
      
      - name: customer_key
        description: "Foreign Key ke tabel dim_customer."
        tests:
          - not_null
          - relationships: # Referential Integrity Check
              to: ref('dim_customer')
              field: customer_key

      - name: product_name
        description: "Foreign Key ke tabel dim_product (berdasarkan nama)."
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_name

      - name: line_total_amount
        description: "Total nilai transaksi per item (Quantity * Unit Price)."
        tests:
          - not_null